feat/GAUSSIAN-FRAME-31
wells-wood-research/aposteriori pull request #34
Opened 2020-10-26 17:41 UTC by universvm

Closes #31

2020-10-29 10:17 UTC, ChrisWellsWood requested changes

2020-11-03 16:13 UTC, ChrisWellsWood reviewed
Looks excellent, great job Leo. Just a few minor points or queries. I'm not going to approve this yet as you and @MichaelJamesStam are due to have your meeting to discuss this later in the week. Well done again, this was clearly a lot of work.

2020-11-03 16:31 UTC, universvm commented on src/aposteriori/data_prep/create_frame_data_set.py
> +    ATOM_WANDERWAAL_RADII,
oops! Thanks for spotting it.

2020-11-03 16:36 UTC, universvm commented on src/aposteriori/config.py
> +ATOMIC_CENTER = (1, 1, 1)
It depends on whether the frame is 3x3x3 or not. My thought was that by adding it as a config variable we could  expand to something slightly larger than that.

2020-11-03 18:02 UTC, universvm commented on src/aposteriori/config.py
> +}
We could change it to a list actually. I just wanted to be explicit about the key.

2020-11-03 18:05 UTC, universvm commented on src/aposteriori/data_prep/create_frame_data_set.py
> +    x_range = y_range = z_range = np.linspace(-range_val, range_val, resolution)
Yeah we could go for `gaussian_range`. I thought this step required additional expciciteness hence why I've assigned a value for each axis.

2020-11-06 14:58 UTC, universvm commented
As per private conversation with @MichaelJamesStam to more things that can be done are:

- [ ]  Add a test for a frame with gaussians 

- [ ]  Do an unoptimized version of `convert_atom_to_gaussian_density` and check that the they both produce the same gaussian frame

2020-11-09 13:45 UTC, ChrisWellsWood submitted a review, later dismissed
This looks great, happy to approve. One thing that popped into my head at the end though, do we have tests for the _original_ (non-gaussian) format? We need protect against a regression.

2020-11-09 13:45 UTC, ChrisWellsWood commented on src/aposteriori/config.py
> +ATOMIC_CENTER = (1, 1, 1)
As we mentioned earlier, I'd remove this and hard code it into the function.

2020-11-09 13:45 UTC, ChrisWellsWood commented on src/aposteriori/data_prep/create_frame_data_set.py
> +                f"{atom_label} not found in {self.atomic_labels} encoding. Returning empty array."
I think the "Returning" part is left over from when it was an error. This won't return anything, as execution is halted by the error unless caught in a `try` statement.

2020-11-09 13:45 UTC, ChrisWellsWood commented on src/aposteriori/data_prep/create_frame_data_set.py
> +    optimized: bool = True,
You don't have any documentation for this flag here.

2020-11-09 13:45 UTC, ChrisWellsWood commented on src/aposteriori/data_prep/create_frame_data_set.py
> +        Whether to encode voxels as gaussians.
As this is the top level function, it is the function that people are most likely to interact with, so it'd be good to have a fully description here, maybe with the citation or explaining the problem it attempts to solve.

2020-11-10 09:17 UTC, ChrisWellsWood approved these changes

2020-11-10 09:18 UTC, merged